# Generated by Django 4.1.7 on 2023-03-23 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="task.project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="worker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
