# Generated by Django 4.1.7 on 2023-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_task_options_remove_project_tasks_task_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(default=None, max_length=64),
        ),
    ]
