# Generated by Django 4.1.7 on 2023-03-26 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_priority"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Priority",
        ),
    ]
